[package]
name = "roombot"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.2"
actix-web = "4.3.1"
gpt_text = "0.1.6"
regex = "1.9.1"
reqwest = "0.11.18"
serde = { version = "1.0.180" , features = ["derive"] }

